-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `cloudmq` DEFAULT CHARACTER SET utf8 ;
USE `cloudmq` ;


CREATE TABLE IF NOT EXISTS `cloudmq`.`registration` (
  `name` VARCHAR(80) NULL,
  `email` VARCHAR(80) NULL,
  `phone` VARCHAR(20) NULL,
  `vin` VARCHAR(20) NOT NULL,
  `password` TEXT NULL,
  `datetime` DATETIME NULL,
  PRIMARY KEY (`vin`))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `cloudmq`.`sensedata` (
  `devid` INT NULL,
  `lpg` TEXT NULL,
  `co` TEXT NULL,
  `smoke` TEXT NULL,
  `datetime` DATETIME NULL,
  `vin` VARCHAR(20) NULL,
  CONSTRAINT `fk_sensedata_registration`
    FOREIGN KEY (`vin`)
    REFERENCES `cloudmq`.`registration` (`vin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
